### ISSUE TITLE
PheanstalkMessage setTimeToRun does'nt work

### ISSUE THREAD

**Issue by m1khal3v** [php-enqueue/pheanstalk#1]
This code doesn't work
public function botAction(Request $request, ProducerInterface $producer)
{
    $decoded = json_decode($request->getContent());
    $message = json_encode($decoded->message, JSON_UNESCAPED_UNICODE);
    $pheanstalkMessage = new PheanstalkMessage($message);
    $pheanstalkMessage->setTimeToRun(60 * 60 * 3);
    $producer->sendCommand(
        Commands::PROCESS_MESSAGE,
        $pheanstalkMessage
    );

    return new Response();
}

This code works well
public function botAction(Request $request, ProducerInterface $producer)
{
    $decoded = json_decode($request->getContent());
    $message = json_encode($decoded->message, JSON_UNESCAPED_UNICODE);
    $pheanstalkMessage = new Message($message);
    $pheanstalkMessage->setHeader('ttr', 60 * 60 * 3);
    $producer->sendCommand(
        Commands::PROCESS_MESSAGE,
        $pheanstalkMessage
    );

    return new Response();
}

**Comment by makasim** [comment]
Please open issue on main repo https://github.com/php-enqueue/enqueue-dev

This one is a read-only mirror. 

Thanks
